name: base
channels:
  - conda-forge
dependencies:
  - ase =3.23.0
  - atomistics =0.1.31
  - black =24.4.2
  - conda-smithy =3.36.2
  - coverage =7.6.0
  - dynaphopy =1.17.15  # [unix]
  - executorlib =0.0.1
  - ffmpeg =7.0.1  # [unix]
  - flux-core =0.64.0  # [linux]
  - flux-sched =0.36.1  # [linux]
  - git =2.45.1
  - git-filter-repo =2.38.0
  - gmailsorter =0.1.3
  - graphviz =11.0.0
  - grayskull =2.5.3
  - gunicorn =22.0.0  # [unix]
  - h5io =0.2.4
  - h5io_browser =0.0.16
  - iprpy-data =2023.07.25
  - jupyterlab =4.2.4
  - lammps =2024.02.07=*openmpi*  # [unix]
  - langchain =0.2.10
  - langchain-anthropic =0.1.20
  - langchain-experimental =0.0.62
  - langchain-openai =0.1.17
  - lxml =5.2.2 
  - mamba =1.5.8
  - matplotlib-base =3.9.1
  - mkl =2023.2.0
  - mpi4py =3.1.6
  - nglview =3.1.2 
  - pyauthenticator =0.2.0  # [unix]
  - pygraphviz =1.13
  - pyiron =0.5.2
  - pyiron-data =0.0.29
  - pyiron_atomistics =0.6.7
  - pyiron_base =0.9.9
  - pymace =0.3.6  # [unix]
  - pymov2gif =0.0.2  # [unix]
  - pysqa =0.1.21
  - python =3.11.8
  - python-ace =0.3.0 # [unix]
  - python-ternary =1.0.8
  - pytorch =2.3.1  # [unix]
  - qe =7.0  # [unix]
  - seaborn =0.13.2
  - sqsgenerator =0.3
  - tensorflow =2.16.1  # [unix]
  - wget =1.21.4  # [unix]
